### ISSUE TITLE
bug: moonbeam -> milkomeda tx status won't load

### ISSUE THREAD

**Issue by anna-carroll** [nomad-xyz/nomad-app#278]
link to GUI which won't load: https://app.nomad.xyz/tx/nomad/moonbeam/0xed1c2490e2e92a485c96186df7e361da4c2ae748123e04cff0cd66cfdf895e01

errors in GUI console:

```
An error occured while getting NomadMessage from Receipt Error: Missing replica for home 1650811245 & remote 25393
    at y.mustGetReplicaFor (NomadContext.js:198:19)
    at new b (NomadMessage.js:73:32)
    at Function.fromReceipt (NomadMessage.js:115:37)
    at Function.fromReceipt (BridgeMessage.js:94:59)
    at Function.singleFromReceipt (BridgeMessage.js:118:40)
    at Function.<anonymous> (BridgeMessage.js:162:34)
    at Generator.next (<anonymous>)
    at i (BridgeMessage.js:5:58)
```

![Screen Shot 2022-04-18 at 11 08 27 AM](https://user-images.githubusercontent.com/11050853/163821964-8db6b5dd-37e7-45e6-8743-9adfb395bd83.png)
![Screen Shot 2022-04-18 at 11 09 12 AM](https://user-images.githubusercontent.com/11050853/163821989-046d00ba-4b81-41e0-acf0-a05456b0401a.png)

**Comment by ErinHales** [comment]
Status loads but shows that it's ready to be processed.  Should show it was processed
